### ISSUE TITLE
Checklist: NiWrap

### ISSUE THREAD

**Issue by birajstha** [nmind/proceedings#10]
### Checklist content

```json
{
  "name": "NiWrap",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/childmindresearch/niwrap"
    },
    {
      "url_type": "Documentation",
      "url": "https://childmindresearch.github.io/niwrap/niwrap.html"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/childmindresearch/niwrap"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": true,
      "2": false,
      "3": false,
      "4": true,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": false,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": false,
      "2": false
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
@kaitj the team reviewed this tool and had the following notes. I updated the json at the top based on this feedback and copied the original below. Please review and approve when you're ready!


Documentation discrepancies:

- continuous integration badge for build status exists in the README w/in python subdirectory but not landing page README, but switched to "true" regardless
- we felt like styxbook had complete documentation on functions, classes, modules, etc. where we looked so marked that as "true"
- switched "Has documented style guide" to "false"; didn't come across one
- Maintenance status isn't documented, so switched to false
- Additional suggestion: the background/significance of program could be expanded upon for accessibility (e.g. people new to neuroimaging might not understand why this utility is important)


Infrastructure discrepancies:

- no explicit DOI for NiWrap itself so switched that to "false"
- no documentation on contributing to NiWrap or Styx compiler available even though the pages exist on the styxbook (the contents are empty), so switched this to "false" (it says [here](https://github.com/childmindresearch/niwrap/blob/main/CONTRIBUTING.md) that this section is a work in progress)
- no Code of Conduct present so switched this to "false"





Original json:

```
{
  "name": "NiWrap",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/childmindresearch/niwrap"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": true,
      "6": true
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": false,
      "4": true,
      "5": true
    }
  },
  "testing": {
    "bronze": {
      "1": false,
      "2": false
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

**Comment by LuciMoore** [comment]
@kaitj actually can you explain more about what qualifies for "Maintenance status is documented?" I assumed it meant that there is a description of how long issues typically take to get resolved, etc, but can this item also be checked if it's clear that issues are being actively responded to?

**Comment by kaitj** [comment]
Your assumption is spot-on - ideally this should be included. It would give a user an idea of response times and the status of the tool (e.g. if it is no longer maintained / deprecated).

**Comment by LuciMoore** [comment]
@kaitj gotcha. ok I'll leave that item marked as false then. I'll let you approve this one in case the developers want to address any issues first
