### ISSUE TITLE
Checklist: HBCD-MADE

### ISSUE THREAD

**Issue by LuciMoore** [nmind/proceedings#17]
### Checklist content

```json
{
  "name": "HBCD-MADE",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://hbcd-made.readthedocs.io/en/latest/"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/DCAN-Labs/HBCD-MADE"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": false,
      "4": false,
      "5": false,
      "6": true
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": false,
      "2": false,
      "3": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": true,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": false,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}

```

### Additional information

Feedback will be provided to developers, who will make improvements and submit updated json

Additional notes to share with MADE developers:

- for HBCD-MADE, the readthedocs should primarily point to https://github.com/DCAN-Labs/HBCD-MADE instead of https://github.com/ChildDevLab/MADE-EEG-preprocessing-pipeline or https://github.com/ChildDevLab/HBCD-MADE
- indicate whether parameters are required or optional
- add license
- add continuous integration

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
Next steps: I'll follow up with the developers to make improvements and resubmit an updated checklist, at which point I'll indicate to the NMIND team that it is ready for their final editorial review

**Comment by kasenetz** [comment]
We have updated the pipeline and associated checklist (copied below). It is now ready for NMIND editorial review @LuciMoore @kaitj

```
{
  "name": "HBCD-MADE",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://hbcd-made.readthedocs.io/en/latest/"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/DCAN-Labs/HBCD-MADE"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": false,
      "2": false,
      "3": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": true,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

**Comment by kaitj** [comment]
@LuciMoore - a few comments and clarification questions here:

* `Documentation / Silver / Supported OSes` - Container recipe is present; item can be ticked off
* `Infrastructure / Bronze / License is present` - License present in the RTD, would also be beneficial to include it in the repository (not a blocking item for approval).
* `Testing`
  * `Bronze`
    * `Test Data` - Just want to double check this; is this the files in the repo or the files being downloaded in the container recipe?
    * `Instructions` - ~Couldn't quite find this.~ Also double checking; are the instructions those in the appendix?
  * `Silver`
    * `Some form of testing suite present` - Could some clarification be provided regarding the testing suite? Able to find some testing matlab testing scripts, but don't see anything that indicates testing.   

I think once some of these are addressed / commented on, approval label can be added.

**Comment by LuciMoore** [comment]
@kaitj Thank you! I updated the top checklist with the checklist I originally provided in the comments (original checklist is copied to bottom of this comment) and made the following updates:

- Marked `Documentation / Silver / Supported OSes` as complete (original checklist is copied to bottom of this comment).
- Unchecked `Testing/Silver/Some form of testing suite` because that was likely just a mistake on my part (I was the one that submitted the original review)

For `Testing/Bronze` items `Test data` and `Instructions`, I marked these as complete based on the tutorial in the Appendix: [HBCD-MADE Local Processing Tutorial]( https://docs-hbcd-made.readthedocs.io/en/latest/appendix.html#hbcd-made-local-processing-tutorial). 

I submitted a a PR https://github.com/DCAN-Labs/HBCD-MADE/pull/18 to rename the Appendix section to "Resources & Tutorial" and add the license to the README. I'm not sure if this answers your questions, so please let me know if not! Otherwise I'll ping you once the PR is merged

I'll follow up with them to make a few changes and get back to you. Let me know if I didn't answer your questions!

<br>
<br>
The original checklist is copied here:

```
{
  "name": "HBCD-MADE",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://docs-hbcd-made.readthedocs.io/en/latest/"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/DCAN-Labs/HBCD-MADE"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/ChildDevLab/MADE-EEG-preprocessing-pipeline"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": false,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": false,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": false,
      "2": false,
      "3": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": true,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

**Comment by kaitj** [comment]
Great that sounds good. I think that clarifies a few things. I’ll wait for the follow up then before taking another look at this one.

**Comment by LuciMoore** [comment]
@kaitj the PR is merged and the webpage is updated, so the top-level json should be accurate as long as you find the Bronze Test items sufficient with these changes. Please approve or lmk if more is needed.. thanks!

**Comment by kaitj** [comment]
Looks good to me!
