### ISSUE TITLE
Checklist: QSIRecon

### ISSUE THREAD

**Issue by madisoth** [nmind/proceedings#21]
### Checklist content

```json
{
  "name": "QSIRecon",
  "urls": [
    {
      "url_type": "Documentation",
      "url": "https://qsirecon.readthedocs.io"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/PennLINC/qsirecon"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": true
    }
  }
}
```

### Additional information

Points discussed with the group at NMIND review:
- A DOI that specifically links to the current version of the software is desired (in addition to a publication DOI, if one was provided)
- Potential for alternatives to JOSS submission requirement (e.g. citing an existing publication DOI)  

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
Next steps: I'll follow up with the developers to make improvements and resubmit an updated checklist, at which point I'll indicate to the NMIND team that it is ready for their final editorial review

**Comment by LuciMoore** [comment]
I updated the json above to check off JOSS submission requirement (e.g. citing an existing publication DOI) as they cite a Nature article instead https://www.nature.com/articles/s41592-021-01185-5

**Comment by LuciMoore** [comment]
Posted issue [here](https://github.com/PennLINC/qsirecon/issues/176)

**Comment by LuciMoore** [comment]
@kaitj the team has resolved the issue posted. I updated the json above and QSIRecon is ready for NMIND review

**Comment by kaitj** [comment]
Some additional comments:

* `documentation/gold/has documented style guide` - similar to `qsiprep`, references fmriprep, but no clickable link - not an issue, just pointing it out here.
* `infrastructure/gold/code of conduct present` - couldn't find anything related to this in the repository or documentation

Looks good to me otherwise - I've updated the checklist to note the code of conduct (see below). If this looks good to you @LuciMoore, happy to add the approve label to this as well once the checklist in the original issue is updated.

```json
{
  "name": "QSIRecon",
  "urls": [
    {
      "url_type": "Documentation",
      "url": "https://qsirecon.readthedocs.io"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/PennLINC/qsirecon"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": true
    }
  }
}
```

**Comment by LuciMoore** [comment]
opened a PR to add link to fmriprep guidelines. once merged I'll update the checklist and approve https://github.com/PennLINC/qsirecon/pull/193

**Comment by LuciMoore** [comment]
@kaitj PR is merged, so the webpage will now include a link to the style guide

I copied your updated json to the json at the top and will mark as approved

If there's something I should be doing differently to make the github actions bot work correctly to close this issue, let me know!

**Comment by kaitj** [comment]
Sounds good - and no I had broken the bot (not automatically closing issues) when i fixed the other issue the other day of it not pushing to the webpage. Just haven't had a chance to look at it yet so have been manually closing as needed for now.
