### ISSUE TITLE
Checklist: QSIPrep

### ISSUE THREAD

**Issue by LuciMoore** [nmind/proceedings#24]
### Checklist content

```json
{
  "name": "QSIPrep",
  "urls": [
    {
      "url_type": "Documentation",
      "url": "https://qsiprep.readthedocs.io"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/PennLINC/qsiprep"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": false,
      "6": true
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": true
    },
    "silver": {
      "1": true,
      "2": false
    },
    "gold": {
      "1": false,
      "2": true
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
Issue submitted to QSIPrep: https://github.com/PennLINC/qsiprep/issues/882

@kaitj for the purposes of HBCD, the only item this repo is missing is a zenodo DOI, so if someone on your team wants to go ahead and perform a final editorial review while you wait on the other HBCD tools to be ready for final review, they can feel free

**Comment by LuciMoore** [comment]
@kaitj QSIPrep is now ready for NMIND review!

**Comment by kaitj** [comment]
Lgtm! Some additional comments:

* `documentation/gold/has a documented style guide`: the contributing doc does refer reader to `fmriprep`'s style guide, but isn't linked - probably a quick fix, but also quick to search up

**Comment by LuciMoore** [comment]
thanks @kaitj I submitted a PR to add a link https://github.com/PennLINC/qsiprep/pull/896 and will re-approve once it's merged

**Comment by LuciMoore** [comment]
@kaitj PR has been merged, so I'll go ahead and approve!
