### ISSUE TITLE
Checklist: nibabies

### ISSUE THREAD

**Issue by mgxd** [nmind/proceedings#25]
### Checklist content

```json
{
  "name": "nibabies",
  "urls": [
    {
      "url_type": "Source code",
      "url": "https://github.com/nipreps/nibabies"
    },
    {
      "url_type": "Documentation",
      "url": "https://nibabies.readthedocs.io/en/latest/"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": false,
      "2": true,
      "3": false,
      "4": true,
      "5": true,
      "6": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": true,
      "4": false,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": false,
      "4": true,
      "5": true
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": false
    },
    "silver": {
      "1": true,
      "2": true
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
@kaitj Nibabies is ready for final NMIND review. it's already listed on the Evaluated Tools page, @mgxd just updated it, so the review should be quick. is the process for approving a tool that's already listed different? like if it's marked as approved on this issue, will the tool then be listed twice [here](https://www.nmind.org/proceedings/)?

**Comment by kaitj** [comment]
The process for approval would remain the same. If there is matching tool name in the proceedings from the updated checklist, it should just update the existing entry.

**Comment by kaitj** [comment]
This one largely looks good to me @LuciMoore. 

Some additional notes:
* Differences from previous evaluation: 
  * `Documentation / Silver / Any alternative usage...` - this is now unchecked. I wasn't sure what (if any) alternative usage there was (unless it refers to the different workflows?) that may have been removed?
  * `Documentation / Gold / Document functions... >= 40%` - this has changed to uncheck, I am assuming from this is due to additions to the code base that are undocumented? I saw a mix of documented + undocumented, but not sure how much code has been added since the last evaluation.
* `Documentation / Gold / ...documented style guide` - There isn't a static reference to this in the repo, but it does reference the Nipreps contributing guidelines, which has a "Coding Style Guide" header. Could consider checking this item as a result.

Otherwise, if this all looks good, can add the approved label.

**Comment by LuciMoore** [comment]
@mgxd can you review @kaitj's notes above please?

**Comment by mgxd** [comment]
> Documentation / Silver / Any alternative usage... - this is now unchecked. I wasn't sure what (if any) alternative usage there was (unless it refers to the different workflows?) that may have been removed?

Yeah, some alternative scripts are present in `scripts/` but are not well documented, so didn't feel it earned it

> Documentation / Gold / Document functions... >= 40% - this has changed to uncheck, I am assuming from this is due to additions to the code base that are undocumented? I saw a mix of documented + undocumented, but not sure how much code has been added since the last evaluation.

I think we're over 40%, so technically could be a check - though I feel like not having an API Reference in the docs should be a blocker (or its own check)

> Documentation / Gold / ...documented style guide - There isn't a static reference to this in the repo, but it does reference the Nipreps contributing guidelines, which has a "Coding Style Guide" header. Could consider checking this item as a result.

Agreed it could go either way, though it should be easy to find - would be nice to add in a [placeholder like fmriprep](https://github.com/nipreps/fmriprep/blob/master/CODE_OF_CONDUCT.md)

@kaitj thanks for the review, let me know what you think - happy to make any changes

**Comment by kaitj** [comment]
@mgxd makes sense regarding the first two documentation items. For documented style guide, I'm with you there too and think it can go either way. Happy to leave this unchecked until there a placeholder is added.

@LuciMoore - this one looks good to be approved!
