### ISSUE TITLE
Checklist: NiftyOne

### ISSUE THREAD

**Issue by paul-reiners** [nmind/proceedings#30]
### Checklist content

```json
{
  "name": "NiftyOne",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/childmindresearch/niftyone/"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/childmindresearch/niftyone/"
    }
  ],
  "documentation": {
    "bronze": {
      "1": false,
      "2": false,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": false,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": false,
      "3": false,
      "4": false,
      "5": true,
      "6": true
    },
    "gold": {
      "1": false,
      "2": false,
      "3": true,
      "4": true,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": true,
      "5": true
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": false
    },
    "silver": {
      "1": true,
      "2": true
    },
    "gold": {
      "1": true,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
this is the final review performed on the initial checklist submission

additional notes are [here](https://drive.google.com/drive/folders/1x0cyaZvprY3FBhMWqs74bRprTg95OeB8?usp=sharing) if the developer would like to review

The reviewer also noted" Listed as having a style guide as part of continuous integration.  But this is Common QL which does static analysis against black-hat hacking."

**Comment by kaitj** [comment]
Thanks - will pass the notes along! Noticed the page deployment didn't trigger when it should have - suspect it may be a repository permissions thing so going to re-add the `approved` label.

**Comment by kaitj** [comment]
> Noticed the page deployment didn't trigger when it should have - suspect it may be a repository permissions thing so going to re-add the approved label.

@LuciMoore - this should be working now.
