### ISSUE TITLE
Checklist: styxdefs

### ISSUE THREAD

**Issue by paul-reiners** [nmind/proceedings#31]
### Checklist content

```json
{
  "name": "styxdefs",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://childmindresearch.github.io/styxdefs"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/childmindresearch/styxdefs"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": false,
      "4": false,
      "5": true,
      "6": true,
      "7": false,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": false,
      "3": false,
      "4": false,
      "5": true,
      "6": false
    },
    "gold": {
      "1": false,
      "2": true,
      "3": true,
      "4": true,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": false,
      "3": false,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": false,
      "2": false
    },
    "silver": {
      "1": true,
      "2": true
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
Final review of checklist submitted [here](https://github.com/nmind/proceedings/issues/18)

Additional notes from @paul-reiners:

- see[ folder ](https://drive.google.com/drive/folders/1Cl6CyYEt1s5kb-yfz6V6hjeDzuag_wkA?usp=sharing)with inspection report outputs (download and open html file with browser to view) 
- For infrastructure, didn't see documented style guide
- Doesn’t specify the version of Python being used.  This wouldn’t be such a big deal, if it weren’t for errors like `Python version 3.9 does not allow writing union types as X | Y`
- There is no requirements.txt nor any other indication of dependencies. (@paul-reiners it looks like you left the related item ("Dependencies listed (i.e., external and within-language requirements)") checked by accident, so I'll modify the json you submitted above to change this item to "false")
- I don’t see tests being run during continuous integration.  CodeQL looks for security vulnerabilities.  It doesn’t run tests.
- I see a list of contributors, but no contribution guide.
- Do not see a code of conduct.
- Do not see test data.

**Comment by LuciMoore** [comment]
@kaitj I took a quick look and I see that there actually is a code of conduct and contribution guide, they just aren't readily accessible via the documentation. I'll leave those as unchecked for now, but should be a quick fix for the developers to point to those in their documentation to get higher marks!

**Comment by kaitj** [comment]
Thanks! CCing @nx10 here so he is aware of the provided notes. Also going to close this issue manually - the approval label with the "Closes" keyword in the commit message should have automatically close this.

Re: Dependencies (I think this is likely the case for a few tools) - Instead of a `requirements.txt`, project metadata and dependencies are found in the `pyproject.toml` file following [PEP 621](https://peps.python.org/pep-0621/).

**Comment by LuciMoore** [comment]
thanks @kaitj I'll share that with the reviewers about the dependencies. should we re-open the issue and mark that item as complete?

**Comment by kaitj** [comment]
> should we re-open the issue and mark that item as complete?

Sure if you're able to, otherwise, we can do it later on.

**Comment by LuciMoore** [comment]
@kaitj I re-opened the issue and marked dependencies as complete in the top json
