### ISSUE TITLE
Checklist: hbcd_motion_postproc

### ISSUE THREAD

**Issue by ohspc89** [nmind/proceedings#6]
### Checklist content

```json
{
  "name": "hbcd_motion_postproc",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/Infant-Neuromotor-Control-Lab/hbcd_motion_postproc"
    }
  ],
  "documentation": {
    "bronze": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false,
      "7": false,
      "8": false,
      "9": false
    },
    "silver": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false,
      "6": false,
      "7": false
    },
    "silver": {
      "1": false,
      "2": false,
      "3": false
    },
    "gold": {
      "1": false,
      "2": false,
      "3": false,
      "4": false,
      "5": false
    }
  },
  "testing": {
    "bronze": {
      "1": false,
      "2": false
    },
    "silver": {
      "1": false,
      "2": false
    },
    "gold": {
      "1": false,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
@ohspc89 we updated this review, but it's pointing to a different repo - see https://github.com/nmind/proceedings/issues/19

can you confirm which repo we should be referencing?

**Comment by ohspc89** [comment]
Thank you. I checked #19. 
If I have to reference the repo I use to maintain the relevant _readthedocs_ page, it should be https://github.com/ohspc89/hbcd_motion_postproc (the one referenced in #19). I initially listed https://github.com/Infant-Neuromotor-Control-Laboratory/hbcd_motion_postproc because this repo has the dockerfile + processing scripts people can use to build containers and the lab will be directing researchers to this repo.

I still think that referencing /Infant-Neuromotor-Control-Laboratory/hbcd_motion_postproc is correct. Please let me know if I should switch.

**Comment by erikglee** [comment]
Hi All, just seeing this now. Sorry @LuciMoore I hadn't realized that the spreadsheet didn't have @ohspc89's latest ReadTheDocs listed. Beyond the github repo Jin just sent over, I think you will largely be interested in reviewing this: https://hbcd-motion-postproc.readthedocs.io/en/latest/index.html

**Comment by LuciMoore** [comment]
@ohspc89 and @erikglee ok so it's my understanding then that the source code and documentation links included in the newer issue (as indicated in the [checklist json](https://github.com/nmind/proceedings/issues/19#issue-2669597389), copied below) are correct, so I will close this issue and we can reference issue 19 moving forward 

```
"name": "hbcd_motion_postproc",
  "urls": [
    {
      "url_type": "Source code",
      "url": "https://github.com/ohspc89/hbcd_motion_postproc"
    },
    {
      "url_type": "Documentation",
      "url": "https://hbcd-motion-postproc.readthedocs.io/en/latest/"
    }
```
