### ISSUE TITLE
Checklist: wristpy

### ISSUE THREAD

**Issue by nx10** [nmind/proceedings#9]
### Checklist content

```json
{
  "name": "wristpy",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/childmindresearch/wristpy"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/childmindresearch/wristpy"
    },
    {
      "url_type": "Documentation",
      "url": "https://childmindresearch.github.io/wristpy/wristpy.html"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false
    },
    "gold": {
      "1": false,
      "2": true,
      "3": true,
      "4": true,
      "5": false,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": false,
      "4": true,
      "5": true
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": false
    },
    "silver": {
      "1": true,
      "2": true
    },
    "gold": {
      "1": true,
      "2": false
    }
  }
}
```

### Agreement

- [X] I agree

**Comment by LuciMoore** [comment]
The final review for this has been performed. The developers can see additional inspection report items [here](https://drive.google.com/drive/folders/1WvUXVrAuqlsiFvi0WeO8JrC63fTKAZhj?usp=sharing)

Additional notes from the final reviewer:

- It’s not clear that typical usage and an example of usage are given although what I see there seems sufficient.
- It’s not clear that the dependencies are listed.  It does have details on the accelerometer details but there is no requirements.txt file for the Python package dependencies.
- No style guide.  I would expect that to be in a contributor’s section.
- Poetry.lock is a generated file.  (And is a lock file, by the way.)  I don’t think it needs to be included in GitHub.
- I’m pretty sure that continuous integration doesn’t validate style.  I see no calls to Pylint or anything like that.  CodeQL checks for security vulnerabilities, not code style.

I've copied the original checklist json is below and will update the json above with the checklist from the final review before marking as approved
```
{
  "name": "wristpy",
  "urls": [
    {
      "url_type": "Landing page",
      "url": "https://github.com/childmindresearch/wristpy"
    },
    {
      "url_type": "Source code",
      "url": "https://github.com/childmindresearch/wristpy"
    },
    {
      "url_type": "Documentation",
      "url": "https://childmindresearch.github.io/wristpy/wristpy.html"
    }
  ],
  "documentation": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": true,
      "7": true,
      "8": true,
      "9": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false
    },
    "gold": {
      "1": false,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false
    }
  },
  "infrastructure": {
    "bronze": {
      "1": true,
      "2": true,
      "3": true,
      "4": true,
      "5": true,
      "6": false,
      "7": true
    },
    "silver": {
      "1": true,
      "2": true,
      "3": true
    },
    "gold": {
      "1": true,
      "2": true,
      "3": false,
      "4": true,
      "5": true
    }
  },
  "testing": {
    "bronze": {
      "1": true,
      "2": false
    },
    "silver": {
      "1": true,
      "2": true
    },
    "gold": {
      "1": true,
      "2": false
    }
  }
}
```

**Comment by kaitj** [comment]
Closing this manually - should have closed with github-actions bot comment.

Will pass along the notes to the authors of the package.

**Comment by shnizzedy** [comment]
> Poetry.lock is a generated file. (And is a lock file, by the way.) I don’t think it needs to be included in GitHub.

Poetry [specifically recommends](https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control) committing the lockfile for applications and encourages it for libraries:

> #### Committing your poetry.lock file to version control
> 
> ##### As an application developer
> Application developers commit `poetry.lock` to get more reproducible builds.
> 
> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then. (See note below about using the update command.)
> 
> > 🚫 If you have added the recommended [`[build-system]`](https://python-poetry.org/docs/pyproject/#poetry-and-pep-517) section to your project’s pyproject.toml then you can successfully install your project and its dependencies into a virtual environment using a command like `pip install -e .`. However, pip will not use the lock file to determine dependency versions as the poetry-core build system is intended for library developers (see next section).
> ##### As a library developer
> Library developers have more to consider. Your users are application developers, and your library will run in a Python environment you don’t control.
> 
> The application ignores your library’s lock file. It can use whatever dependency version meets the constraints in your `pyproject.toml`. The application will probably use the latest compatible dependency version. If your library’s `poetry.lock` falls behind some new dependency version that breaks things for your users, you’re likely to be the last to find out about it.
> 
> A simple way to avoid such a scenario is to omit the `poetry.lock` file. However, by doing so, you sacrifice reproducibility and performance to a certain extent. Without a lockfile, it can be difficult to find the reason for failing tests, because in addition to obvious code changes an unnoticed library update might be the culprit. Further, Poetry will have to lock before installing a dependency if `poetry.lock` has been omitted. Depending on the number of dependencies, locking may take a significant amount of time.
> 
> If you do not want to give up the reproducibility and performance benefits, consider a regular refresh of `poetry.lock` to stay up-to-date and reduce the risk of sudden breakage for users.
